import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Calendar, Clock, BookOpen, Target, ArrowRight } from 'lucide-react'
import Link from 'next/link'

const examplePlans = [
  {
    id: 1,
    title: 'Mathematics Study Plan',
    description: 'Comprehensive math preparation for calculus and algebra',
    subjects: ['Calculus', 'Linear Algebra'],
    duration: '4 weeks',
    dailyHours: 3,
    level: 'Undergraduate',
    features: [
      'Daily problem-solving practice',
      'Concept review and reinforcement',
      'Practice tests and quizzes',
      'Visual learning with graphs and diagrams'
    ],
    schedule: {
      'Week 1': 'Calculus fundamentals and derivatives',
      'Week 2': 'Integration techniques and applications',
      'Week 3': 'Linear algebra basics and matrix operations',
      'Week 4': 'Advanced topics and comprehensive review'
    }
  },
  {
    id: 2,
    title: 'Science Study Plan',
    description: 'Balanced approach to biology and chemistry learning',
    subjects: ['Biology', 'Chemistry'],
    duration: '6 weeks',
    dailyHours: 4,
    level: 'High School',
    features: [
      'Laboratory concept reinforcement',
      'Visual diagrams and flowcharts',
      'Practice problems and experiments',
      'Regular review sessions'
    ],
    schedule: {
      'Week 1-2': 'Cell biology and basic chemistry',
      'Week 3-4': 'Genetics and organic chemistry',
      'Week 5-6': 'Ecology and chemical reactions'
    }
  },
  {
    id: 3,
    title: 'Language Arts Study Plan',
    description: 'Comprehensive English and literature preparation',
    subjects: ['English Literature', 'Grammar', 'Writing'],
    duration: '5 weeks',
    dailyHours: 2,
    level: 'High School',
    features: [
      'Reading comprehension practice',
      'Essay writing techniques',
      'Grammar and vocabulary building',
      'Literary analysis skills'
    ],
    schedule: {
      'Week 1': 'Grammar fundamentals and sentence structure',
      'Week 2-3': 'Reading comprehension and analysis',
      'Week 4': 'Essay writing and composition',
      'Week 5': 'Literature review and final practice'
    }
  }
]

export default function Examples() {
  return (
    <div className="container mx-auto px-4 py-12 pt-36">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4 font-space-grotesk text-gray-900">
          <span className="text-gray-900">Study</span><span className="bg-gradient-to-r from-studypal-blue to-studypal-cyan bg-clip-text text-transparent">Pal</span> Plan Showcase
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Explore real study plans generated by StudyPal AI for different academic levels and subjects. 
          See how our AI creates personalized, comprehensive study strategies.
        </p>
      </div>

      <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-8 mb-12 max-w-7xl mx-auto">
        {examplePlans.map((plan) => (
          <Card key={plan.id} className="border-0 shadow-lg hover:shadow-xl transition-shadow">
            <CardHeader>
              <div className="flex justify-between items-start mb-2">
                <CardTitle className="text-xl">{plan.title}</CardTitle>
                <Badge variant="outline">{plan.level}</Badge>
              </div>
              <CardDescription className="text-base">
                {plan.description}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Plan Overview */}
              <div className="grid grid-cols-2 gap-4">
                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-blue-600" />
                  <span className="text-sm font-medium">{plan.duration}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4 text-green-600" />
                  <span className="text-sm font-medium">{plan.dailyHours}h/day</span>
                </div>
              </div>

              {/* Subjects */}
              <div>
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <BookOpen className="h-4 w-4" />
                  Subjects Covered
                </h4>
                <div className="flex flex-wrap gap-2">
                  {plan.subjects.map((subject, index) => (
                    <Badge key={index} variant="secondary">
                      {subject}
                    </Badge>
                  ))}
                </div>
              </div>

              {/* Key Features */}
              <div>
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <Target className="h-4 w-4" />
                  Key Features
                </h4>
                <ul className="space-y-1">
                  {plan.features.map((feature, index) => (
                    <li key={index} className="text-sm text-gray-600 flex items-start gap-2">
                      <span className="w-1.5 h-1.5 bg-blue-600 rounded-full mt-2 flex-shrink-0"></span>
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Schedule Overview */}
              <div>
                <h4 className="font-semibold mb-2">Study Schedule</h4>
                <div className="space-y-2">
                  {Object.entries(plan.schedule).map(([period, description], index) => (
                    <div key={index} className="text-sm">
                      <span className="font-medium text-blue-600">{period}:</span>
                      <span className="text-gray-600 ml-2">{description}</span>
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* CTA Section */}
      <div className="text-center bg-blue-50 rounded-2xl p-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          Ready to Create Your Own Study Plan?
        </h2>
        <p className="text-gray-600 mb-6 max-w-2xl mx-auto">
          These are just examples of what StudyPal AI can create. Get your personalized study plan 
          tailored to your specific subjects, schedule, and learning goals.
        </p>
        <Button asChild size="lg">
          <Link href="/study-assistant">
            Create My Study Plan <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </Button>
      </div>

    </div>
  )
}